---
# https://github.com/pyenv/pyenv/wiki
- name: Install build depends (homebrew)
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - tcl-tk
      - xz
      - zlib

- name: Update build args
  set_fact:
    build_args: >-
      {{ build_args }}
      --with-openssl=$(brew --prefix openssl)
