---
- name: Check Python installed
  stat:
    path: /usr/local/bin/python
  register: bin_python

# https://github.com/pyenv/pyenv/wiki
- name: Install build depends
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - curl
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - llvm
    - make
    - tk-dev
    - wget
    - xz-utils
    - zlib1g-dev
become: yes
  when: not bin_python.stat.exists

- name: Create tempfile
  tempfile:
    state: directory
  register: tempfile
  when: not bin_python.stat.exists

- name: Download Python source
  shell: >-
    curl -L https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz | tar xzf -
  args:
    chdir: "{{ tempfile.path }}"
    creates: "{{ tempfile.path }}/Python-{{ python_version }}"
  when: not bin_python.stat.exists

- name: Build Python
  shell: |
    ./configure
    make -j
  args:
    chdir: "{{ tempfile.path }}/Python-{{ python_version }}"
  when: not bin_python.stat.exists

- name: Install Python
  shell: make install
  args:
    chdir: "{{ tempfile.path }}/Python-{{ python_version }}"
  become: yes
  when: not bin_python.stat.exists
