---
- name: Check Python installed
  stat:
    path: "{{ install_prefix }}/bin/python3"
  register: bin_python

- fail:
    msg: OS is Unsupported.
  when: |
    not bin_python.stat.exists
    and ansible_facts['os_family'] != "Debian"

- include_tasks: install.yaml
  when: not bin_python.stat.exists
