on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install ansible
      - run: |
          cd ..
          ansible-playbook ansible-role-python/tests/test.yaml
          ansible-playbook ansible-role-python/tests/test.yaml | tail -2 | grep changed=0
