on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install ansible
      - name: Run playbook
        run: |
          cd ..
          ansible-playbook ansible-role-python/tests/test.yaml
      - name: Rerun playbook and no changed tasks
        run: |
          cd ..
          ansible-playbook ansible-role-python/tests/test.yaml | tail -2 | grep changed=0
